import {
  Download,
  FileDown,
  FileText,
  ShieldCheck,
} from "lucide-react";

import DashboardLayout from "../components/DashboardLayout";

function CivicDownloadReports({
  reports = [],
}) {
  function downloadReport(report) {
    const analysis = report.analysis || {};

    const content = `
CIVICVISION CIVIC REPORT
========================

Report ID:
${report.id || "N/A"}

Issue Type:
${report.issueType || "N/A"}

Status:
${report.status || "N/A"}

Created:
${report.createdAt || "N/A"}

Civic Points:
${report.points || 0}

AI Detection:
${analysis.detection || report.issueType || "N/A"}

AI Confidence:
${analysis.confidence || 0}%

Severity:
${analysis.severity || "N/A"}

Safety Risk:
${analysis.risk || "N/A"}

Priority:
${analysis.priority || "N/A"}

Bin Status:
${analysis.binStatus || "N/A"}

Location:
${
  report.location
    ? `${report.location.lat}, ${report.location.lon}`
    : "Not available"
}

Description:
${report.description || "N/A"}

========================
Generated by CivicVision
`;

    const blob = new Blob(
      [content],
      {
        type: "text/plain",
      }
    );

    const url =
      URL.createObjectURL(blob);

    const link =
      document.createElement("a");

    link.href = url;

    link.download =
      `${report.id || "civic-report"}.txt`;

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  function downloadAllReports() {
    if (reports.length === 0) {
      return;
    }

    const content = reports
      .map((report) => {
        const analysis =
          report.analysis || {};

        return `
----------------------------------------
CIVICVISION REPORT
----------------------------------------

Report ID: ${report.id || "N/A"}
Issue: ${report.issueType || "N/A"}
Status: ${report.status || "N/A"}
Created: ${report.createdAt || "N/A"}
Civic Points: ${report.points || 0}

AI Detection:
${analysis.detection || report.issueType || "N/A"}

Confidence:
${analysis.confidence || 0}%

Severity:
${analysis.severity || "N/A"}

Safety Risk:
${analysis.risk || "N/A"}

Priority:
${analysis.priority || "N/A"}

Bin Status:
${analysis.binStatus || "N/A"}

Description:
${report.description || "N/A"}
`;
      })
      .join("\n");

    const finalContent = `
CIVICVISION
CITIZEN REPORT ARCHIVE

${content}

----------------------------------------
Generated by CivicVision
----------------------------------------
`;

    const blob = new Blob(
      [finalContent],
      {
        type: "text/plain",
      }
    );

    const url =
      URL.createObjectURL(blob);

    const link =
      document.createElement("a");

    link.href = url;

    link.download =
      "civicvision-reports.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  return (
    <DashboardLayout
      title="Download Reports"
      subtitle="Export your CivicVision civic reports and AI verification records."
    >
      {/* SUMMARY */}
      <div className="download-summary-grid">

        <div className="dashboard-card download-stat">

          <div className="download-stat-icon">
            <FileText size={23} />
          </div>

          <div>
            <span>
              TOTAL REPORTS
            </span>

            <strong>
              {reports.length}
            </strong>

            <small>
              Available for export
            </small>
          </div>

        </div>

        <div className="dashboard-card download-stat">

          <div className="download-stat-icon">
            <ShieldCheck size={23} />
          </div>

          <div>
            <span>
              AI VERIFIED
            </span>

            <strong>
              {
                reports.filter(
                  (report) =>
                    report.analysis
                      ?.authentic !== false
                ).length
              }
            </strong>

            <small>
              Verified evidence
            </small>
          </div>

        </div>

      </div>

      {/* EXPORT ALL */}
      <div className="dashboard-card download-all-card">

        <div className="download-all-icon">
          <FileDown size={28} />
        </div>

        <div className="download-all-content">

          <span className="card-eyebrow">
            REPORT ARCHIVE
          </span>

          <h2>
            Download all reports
          </h2>

          <p>
            Export your complete CivicVision
            report history as a text archive.
          </p>

        </div>

        <button
          className="primary-button"
          onClick={
            downloadAllReports
          }
          disabled={
            reports.length === 0
          }
        >
          <Download size={18} />

          {reports.length === 0
            ? "No Reports"
            : "Download All"}
        </button>

      </div>

      {/* REPORT LIST */}
      <div className="dashboard-card download-list-card">

        <div className="section-header">

          <div>

            <span className="card-eyebrow">
              YOUR REPORTS
            </span>

            <h2>
              Available exports
            </h2>

          </div>

          <FileText size={23} />

        </div>

        {reports.length === 0 ? (

          <div className="download-empty">

            <div className="download-empty-icon">
              <FileText size={25} />
            </div>

            <h3>
              No reports available
            </h3>

            <p>
              Submit your first civic report
              and it will appear here.
            </p>

          </div>

        ) : (

          <div className="download-report-list">

            {reports.map((report) => (

              <div
                className="download-report-item"
                key={report.id}
              >

                <div className="download-report-icon">
                  <FileText size={20} />
                </div>

                <div className="download-report-info">

                  <strong>
                    {report.issueType}
                  </strong>

                  <span>
                    {report.id}
                  </span>

                  <small>
                    {report.createdAt}
                  </small>

                </div>

                <div className="download-report-status">

                  <span>
                    {report.status ||
                      "Submitted"}
                  </span>

                  <b>
                    +{report.points || 0}
                    {" "}
                    Points
                  </b>

                </div>

                <button
                  className="icon-action-button"
                  title="Download report"
                  onClick={() =>
                    downloadReport(
                      report
                    )
                  }
                >
                  <Download
                    size={18}
                  />
                </button>

              </div>

            ))}

          </div>

        )}

      </div>

    </DashboardLayout>
  );
}

export default CivicDownloadReports;